title: Migun Shakya
description: Migun Shakya page
baseurl: ""
url: https://mshakya.github.io

theme: cvless

# site settings
taglong: Scientist, Bioscience Division, Los Alamos National Laboratory
tagshort: Scintist
cv: true

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/files/photo.jpg
address: Bioscience Division, Los Alamos National Laboratory
phone: +1 234 567 890

# profile links
profile:
  # facebook: https://www.facebook.com/username
  # x: https://x.com/username
  # mastodon: https://mastodon.social/@username
  bluesky: https://bsky.app/profile/username.bsky.social
  # instagram: https://www.instagram.com/username
  linkedin: https://www.linkedin.com/in/migun
  # xing: https://www.xing.com/profile/username
  scholar: https://scholar.google.com/citations?user=5eGzndAAAAAJ&hl=en
  # medium: https://medium.com/@username
  github: https://github.com/mshakya
  orcid: https://orcid.org/0000-0003-3876-691X

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
